### ISSUE TITLE
Missing generate_appcast

### ISSUE THREAD

**Issue by aspnetman** [oodrive/SparkleSharp#3]
I have an question. In [documentation ](https://github.com/oodrive/SparkleSharp)I have read that I need follow Sparkle's own documentation to set your appcast URL and add a "Check for Updates" menu item.
In that documentation I read:

_Run generate_appcast tool from Sparkle’s distribution archive specifying the path to the folder with update archives. Allow it to access the Keychain if it asks for it (it’s needed to generate signatueres in the appcast).
./bin/generate_appcast /path/to/your/updates_folder/_

But I don't have generate_appcast file in Sparkles bin folder, only generate_keys and sign_update.
What I'm doing wrong?

![image](https://user-images.githubusercontent.com/52282641/138276406-70ab9fc6-9aef-427c-ba8b-c6712ffeee70.png)

**Comment by Odirb** [comment]
Hello,
You will find the generate_keys in sparkles release package : (this one for example https://github.com/sparkle-project/Sparkle/releases/tag/1.27.1)
